name: Build
on:
  push:
    branches:
      - master
      - '*.x'
    tags:
      - '*'
jobs:
  wheels:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      CIBW_SKIP: 'cp27-* pp27-* cp35-*'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install cibuildwheel
      - run: cibuildwheel
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse

  wheels_aarch64:
    name: ${{ matrix.os }}-aarch64
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Docker Buildx
        id: Buildx
        uses: crazy-max/ghaction-docker-buildx@v3.3.0
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Use docker to install and emulate AArch64 tests
        run: |
          docker buildx build --platform linux/arm64 -t markupsafe_aarch64 --output tmpwheelhouse -f .github/workflows/Dockerfile_aarch64_build .
          mkdir -p wheelhouse
          mv tmpwheelhouse/wheelhouse/*.whl wheelhouse/
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse
